import type { Metadata } from "next";
import "../../styles/globals.css";



export const metadata: Metadata = {
  title: "template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-zinc-800 text-white`}
      >
        {children}
      </body>
    </html>
  );
}
