import type { Metadata } from "next";
import "@/styles/globals.css";
import {Open_Sans} from "next/font/google"; 

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
